name: Release

on:
  push:
    branches: [main]

permissions:
  contents: write
  pull-requests: write
  id-token: write  # required for npm provenance

jobs:
  release:
    name: Version & Publish
    runs-on: ubuntu-latest
    environment: npm-publish   # protect this environment with required reviewers
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'
          cache: 'pnpm'
          cache-dependency-path: '**/pnpm-lock.yaml'

      - name: Install
        run: pnpm install --frozen-lockfile

      # This action either opens/updates the "Version Packages" PR,
      # or, if we're on main AND that PR has been merged, it will run "pnpm release"
      - name: Changesets
        id: changesets
        uses: changesets/action@v1
        with:
          publish: pnpm release --tag next # 👈 temporarilyadd --tag next for prereleases
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
